### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by ggeudens** [sdebruyn/homeassistant-bpost-integration#36] opened 2022-01-14 09:59 UTC
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.bpost.config_flow
Source: custom_components/bpost/config_flow.py:46
Integration: bpost Mijn Post & zendingen (documentation, issues)
First occurred: 10:53:06 (2 occurrences)
Last logged: 10:56:10

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/bpost/config_flow.py", line 94, in async_step_user
    info = await validate_email(self.hass, user_input)
  File "/config/custom_components/bpost/config_flow.py", line 46, in validate_email
    await bpost_api.async_users_email_login()
  File "/usr/local/lib/python3.9/site-packages/my_bpost_api/bpost_api.py", line 124, in async_users_email_login
    response = await self._async_send_request(
  File "/usr/local/lib/python3.9/site-packages/my_bpost_api/bpost_api.py", line 98, in _async_send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://mbassapi.bpost.be/prod_v2/users/emaillogin')

**Comment by ggeudens** [comment] 2022-01-14 10:02
Error during login. Email is correct. 
![Screenshot_2022-01-14-11-01-26-03_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/71509610/149497169-714e677d-3b69-4a3b-a8f5-cd93731c6b97.jpg)

**Comment by sdebruyn** [comment] 2022-01-14 10:08
Same, it's broken for me as well since today. Duplicate of #35

**Closed by sdebruyn** 2022-01-14 10:08 UTC
